sudo: false
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_ef39d1faaf57_key -iv $encrypted_ef39d1faaf57_iv
  -in client-secret.json.enc -out client-secret.json -d
deploy:
  provider: gae
  keyfile: client-secret.json
  project: tmmscw-179613
  on: design
