# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0010_usercommand_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0422\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='tmuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439'),
        ),
        migrations.AlterField(
            model_name='usercommand',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tmmoscow.Team', verbose_name='\u041a\u043e\u043c\u0430\u043d\u0434\u0430'),
        ),
    ]
