# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0013_auto_20180101_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdistance',
            options={'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430 \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430 \u043d\u0430 \u0434\u0438\u0441\u0442\u0430\u043d\u0446\u0438\u044e', 'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430 \u043d\u0430 \u0434\u0438\u0441\u0442\u0430\u043d\u0446\u0438\u044e'},
        ),
        migrations.AlterModelTable(
            name='userdistance',
            table='tm_user_distance',
        ),
    ]
