# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0016_userdistance_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdistance',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members_on_distance', to='tmmoscow.Team', verbose_name='\u041a\u043e\u043c\u0430\u043d\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='userdistance',
            name='distance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tmmoscow.Distance', verbose_name='\u0414\u0438\u0441\u0442\u0430\u043d\u0446\u0438\u044f'),
        ),
    ]
