# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmuser',
            name='birth',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0413\u043e\u0434 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
    ]
