# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0002_auto_20171028_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmuser',
            name='qual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tmmoscow.Qualification', verbose_name='\u0420\u0430\u0437\u0440\u044f\u0434'),
        ),
    ]
