# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0003_auto_20171028_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmuser',
            name='is_org',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0442\u043e\u0440'),
        ),
    ]
