# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0004_auto_20171028_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('location', models.CharField(max_length=512, verbose_name='\u0422\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u044f')),
                ('geo_x', models.CharField(blank=True, max_length=16, null=True, verbose_name='X-\u043a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u0430')),
                ('geo_y', models.CharField(blank=True, max_length=16, null=True, verbose_name='Y-\u043a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='UserCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False, verbose_name='\u042f\u0432\u043b\u044f\u0435\u0442\u0441\u044f \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u0435\u043c')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmmoscow.Team', verbose_name='\u041a\u043e\u043c\u0430\u043d\u0434\u0430')),
            ],
        ),
    ]
