# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0005_team_usercommand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '\u041a\u043e\u043c\u0430\u043d\u0434\u0430', 'verbose_name_plural': '\u041a\u043e\u043c\u0430\u043d\u0434\u044b'},
        ),
        migrations.AlterModelOptions(
            name='usercommand',
            options={'verbose_name': '\u041a\u043e\u043c\u0430\u043d\u0434\u0430-\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a', 'verbose_name_plural': '\u041a\u043e\u043c\u0430\u043d\u0434\u0430-\u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0438'},
        ),
        migrations.AlterModelTable(
            name='team',
            table='tm_team',
        ),
        migrations.AlterModelTable(
            name='usercommand',
            table='tm_user_team',
        ),
    ]
