# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0006_auto_20171117_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommand',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='tmmoscow.Team', verbose_name='\u041a\u043e\u043c\u0430\u043d\u0434\u0430'),
        ),
    ]
