# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0008_usercommand_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercommand',
            name='user',
        ),
    ]
