# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0009_remove_usercommand_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommand',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='\u0423\u0447\u0430\u0441\u0442\u0438\u043a'),
        ),
    ]
