# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0014_auto_20180101_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmuser',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u041c\u0443\u0436\u0441\u043a\u043e\u0439'), (1, '\u0416\u0435\u043d\u0441\u043a\u0438\u0439')], default=0, verbose_name='\u041f\u043e\u043b'),
        ),
    ]
