# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmmoscow', '0015_tmuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdistance',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u044f\u0432\u043a\u0438'),
        ),
    ]
